// Mocks generated by Mockito 5.3.2 from annotations
// in applifting_assignment/test/app/company_info/presentation/bloc/company_info_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:applifting_assignment/app/company_info/domain/company_info.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'company_info_bloc_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCompanyInfo_0 extends _i1.SmartFake implements _i2.CompanyInfo {
  _FakeCompanyInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockCompanyInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockCompanyInfoService extends _i1.Mock
    implements _i3.MockCompanyInfoService {
  MockMockCompanyInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CompanyInfo> getCompanyInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCompanyInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.CompanyInfo>.value(_FakeCompanyInfo_0(
          this,
          Invocation.method(
            #getCompanyInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CompanyInfo>);
  @override
  _i4.Future<void> openWebPage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #openWebPage,
          [url],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
